global using LibraryManagementSystem.Database.AppDbContextModels;
global using LibraryManagementSystem.Domain.Models.User;
global using LibraryManagementSystem.Domain.Models;
global using Microsoft.EntityFrameworkCore;
global using LibraryManagementSystem.Domain.Models.Category;
global using LibraryManagementSystem.Domain.Models.Book;
global using LibraryManagementSystem.Domain.Models.Transaction;
global using LibraryManagementSystem.Domain.Models.Return;
global using LibraryManagementSystem.Domain.Models.Borrow;
